### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by Mwesome** [neoxic/php-amf3#14]
As the data grows big the memory consumption becomes alot.
Is there anyway to decrease the memory consumption?

**Comment by neoxic** [comment]
Hm... Stop the data growth?

**Comment by Mwesome** [comment]
the data is already big :/
multiple files and some of them are kinda big like 70mb big and the decoded object becomes hugeeeeee
i run out of memory before decoding it :v
anyways thnx for the extension , was like a light of hope in my despair :v

**Comment by neoxic** [comment]
I can't see why you may need PHP to decode such big files. Any such decoding will consume a lot of time, leave aside memory consumption and extreme server load, if served to public clients. Hence, it will bring nothing but problems due to bad system design.

If it's for once-in-a-while console applications like parsing logs or reports, you can always increase PHP memory limits via the PHP configuration directive `memory_limit`.
